// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PrettyDocComments.Commands
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPrettyDocCommentsPackageString = "795b02f0-c2f6-48d6-88f8-07df405312ec";
        public static Guid guidPrettyDocCommentsPackage = new Guid(guidPrettyDocCommentsPackageString);

        public const string guidPrettyDocCommentsPackageCmdSetString = "54d1f8d3-3afd-431f-adc9-5e5236c31dad";
        public static Guid guidPrettyDocCommentsPackageCmdSet = new Guid(guidPrettyDocCommentsPackageCmdSetString);

        public const string guidImagesString = "ab905840-176d-423c-be7c-853d0d866680";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int ToggleCollapseCommentId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}