---
title: Workflow of doc comment detection and rendering
---
flowchart TD
    D_Text(["<code>IWpfTextView.TextSnapshot</code><br/><small>C# VB F# C++</small>"])
    OP_Loc["<code>Locator</code><br/><small>detects doc comments</small>"]
    D_CmtStr(["<code>Comment&lt;string&gt;</code><br/><small>as XML</small>"])
    OP_XParse["<code>XDocument.Parse</code>"]
    D_CmtXNodes(["<code>Comment&lt;IEnumerable&lt;XNode&gt;&gt;</code>"])
    OP_ShpParse["<code>ShapeParser</code><br/><small><code>FormatParser<br/>FormatAccumulator<br/>WidthEstimator</code></small>"]
    D_CmtShapes(["<code>Comment&lt;List&lt;Shape&gt;&gt;</code>"])
    OP_Render1["<code>Renderer.GetRenderInfo</code>"]

    D_AdornerRndrInf(["<code>List&lt;Comment&lt;RenderInfo&gt;&gt;</code><br/><small><code>Adorner.RenderingInformation</code></small>"])
    D_TextView(["<code>IWpfTextView.TextViewLines</code>"])

    OP_Render2["<code>Renderer.Render</code>"]
    D_CmtImg(["<code>Comment&lt;Image&gt;</code>"])

    D_AdornerLyr(["<code>IAdornmentLayer</code>"])

    D_Text --> SUB_LT --> D_AdornerRndrInf --> SUB_AD --> D_AdornerLyr
    D_TextView --> SUB_AD

    D_Text ~~~ SUB_Legend

    subgraph SUB_Legend [Legend]
     SO["&nbsp;Operation / Service&nbsp;"]
     ~~~
     SD(["&nbsp;&nbsp;&nbsp;&nbsp;Data&nbsp;&nbsp;&nbsp;&nbsp;"])
    end

    subgraph SUB_LT ["<code>LineTransformSource</code>"]
       OP_Loc --> D_CmtStr --> OP_XParse --> D_CmtXNodes -->
       OP_ShpParse --> D_CmtShapes --> OP_Render1
    end

    subgraph SUB_AD ["<code>Adornment</code>"]
        OP_Render2 --> D_CmtImg
    end    
